version: 2

project_name: snagify

before:
  hooks:
    - go mod tidy

builds:
  - id: snagify
    main: .
    binary: snagify
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: snagify
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE

checksum:
  name_template: checksums.txt
  algorithm: sha256

dockers:
  - id: snagify-amd64
    use: buildx
    goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/HarshDevelops/snagify:{{ .Version }}-amd64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=snagify"
      - "--label=org.opencontainers.image.description=Single-binary CLI to debug works-on-my-machine issues by detecting environment drift."
      - "--label=org.opencontainers.image.source=https://github.com/HarshDevelops/snagify"
      - "--label=org.opencontainers.image.licenses=MIT"
    extra_files:
      - README.md
      - CHANGELOG.md
      - LICENSE
  - id: snagify-arm64
    use: buildx
    goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    image_templates:
      - "ghcr.io/HarshDevelops/snagify:{{ .Version }}-arm64"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.title=snagify"
      - "--label=org.opencontainers.image.description=Single-binary CLI to debug works-on-my-machine issues by detecting environment drift."
      - "--label=org.opencontainers.image.source=https://github.com/HarshDevelops/snagify"
      - "--label=org.opencontainers.image.licenses=MIT"
    extra_files:
      - README.md
      - CHANGELOG.md
      - LICENSE

docker_manifests:
  - name_template: "ghcr.io/HarshDevelops/snagify:{{ .Version }}"
    image_templates:
      - "ghcr.io/HarshDevelops/snagify:{{ .Version }}-amd64"
      - "ghcr.io/HarshDevelops/snagify:{{ .Version }}-arm64"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc

release:
  draft: true
  replace_existing_draft: true
  prerelease: auto
  name_template: "Snagify {{ .Version }}"
