// Package initcfg generates a conservative starter .snagify.yaml from a
// captured snapshot and the project's detected manifests.
package initcfg

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/harshdevelops/snagify/internal/capture"
	"github.com/harshdevelops/snagify/internal/model"
)

// manifestRuntimes maps a manifest filename to the runtimes it implies.
var manifestRuntimes = map[string][]string{
	"package.json":     {"node", "npm"},
	"go.mod":           {"go"},
	"pom.xml":          {"java", "maven"},
	"build.gradle":     {"java", "gradle"},
	"build.gradle.kts": {"java", "gradle"},
	"requirements.txt": {"python"},
	"pyproject.toml":   {"python"},
	"Cargo.toml":       {"rust", "cargo"},
}

// dockerMarkers indicate a Docker requirement when present in the root.
var dockerMarkers = []string{"docker-compose.yml", "docker-compose.yaml", "compose.yml", "compose.yaml", "Dockerfile"}

// Generate builds a conservative .snagify.yaml document from snap and the files
// present in projectRoot. It never includes secret values or absolute paths.
func Generate(snap model.Snapshot, projectRoot string) string {
	runtimes := detectRuntimes(snap, projectRoot)

	var b strings.Builder
	b.WriteString("# Generated by `snagify init`. Review and adjust before committing.\n")
	b.WriteString("version: 1\n")
	b.WriteString("project:\n")
	b.WriteString(fmt.Sprintf("  name: %s\n", yamlString(projectName(snap, projectRoot))))

	if len(runtimes) > 0 {
		b.WriteString("runtimes:\n")
		keys := make([]string, 0, len(runtimes))
		for k := range runtimes {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			b.WriteString(fmt.Sprintf("  %s: %s\n", k, yamlString(runtimes[k])))
		}
	}

	// Env section if an example file exists.
	if exampleFile, keys, ok := detectEnv(projectRoot); ok {
		b.WriteString("env:\n")
		b.WriteString(fmt.Sprintf("  example_file: %s\n", yamlString(exampleFile)))
		b.WriteString("  actual_file: \".env\"\n")
		if len(keys) > 0 {
			b.WriteString("  required:\n")
			for _, k := range keys {
				b.WriteString(fmt.Sprintf("    - %s\n", k))
			}
		}
	}

	b.WriteString("ports:\n")
	b.WriteString("  must_be_free: []\n")
	b.WriteString("  must_be_listening: []\n")

	b.WriteString("git:\n")
	b.WriteString("  require_clean: false\n")
	b.WriteString("  warn_if_wrong_branch: false\n")

	return b.String()
}

// detectRuntimes returns a map of runtime name -> requirement. Detected runtimes
// use ">=<major>" from the captured version when present, else "required".
func detectRuntimes(snap model.Snapshot, root string) map[string]string {
	out := map[string]string{}
	for _, m := range snap.Project.Manifests {
		for _, rt := range manifestRuntimes[m] {
			out[rt] = requirementFor(snap, rt)
		}
	}
	for _, marker := range dockerMarkers {
		if fileExists(filepath.Join(root, marker)) {
			out["docker"] = "required"
			break
		}
	}
	return out
}

func requirementFor(snap model.Snapshot, rt string) string {
	info, known := model.LookupRuntime(snap.Runtimes, rt)
	if known && info.Present {
		if major := majorOf(info.Version); major != "" {
			return ">=" + major
		}
	}
	return "required"
}

func majorOf(version string) string {
	v := strings.TrimSpace(version)
	if v == "" {
		return ""
	}
	if i := strings.IndexByte(v, '.'); i > 0 {
		v = v[:i]
	}
	if _, err := strconv.Atoi(v); err != nil {
		return ""
	}
	return v
}

// detectEnv returns the example file name and its declared keys (names only).
func detectEnv(root string) (string, []string, bool) {
	for _, name := range []string{".env.example", ".env.sample", ".env.template"} {
		p := filepath.Join(root, name)
		if fileExists(p) {
			keys, _ := capture.ReadEnvKeys(p)
			return name, keys, true
		}
	}
	return "", nil, false
}

func projectName(snap model.Snapshot, root string) string {
	if snap.Project.Name != "" {
		return snap.Project.Name
	}
	return filepath.Base(root)
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

// yamlString quotes a value for safe single-line YAML output.
func yamlString(s string) string {
	if s == "" {
		return `""`
	}
	// Always quote to be safe with version operators like ">=20".
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}
